/*
 * Copyright (C) 2016+     AzerothCore <www.azerothcore.org>, released under GNU GPL v2 license: https://github.com/azerothcore/azerothcore-wotlk/blob/master/LICENSE-GPL2
 */

// This file is autogenerated, please do not modify directly!

// Added modules includes
@AC_SCRIPTS_INCLUDES@

// Add default scripts
@AC_SCRIPTS_LIST@

void AddScripts()
{
    // Added module and default scripts
    @AC_ADD_SCRIPTS_LIST@
}
