#ifndef __LOGIN_HOLDER_ENUM
#define __LOGIN_HOLDER_ENUM

enum PlayerLoginQueryIndex
{
    PLAYER_LOGIN_QUERY_LOADFROM                 = 0,
    PLAYER_LOGIN_QUERY_LOADGROUP                = 1,
    PLAYER_LOGIN_QUERY_LOADBOUNDINSTANCES       = 2,
    PLAYER_LOGIN_QUERY_LOADAURAS                = 3,
    PLAYER_LOGIN_QUERY_LOADSPELLS               = 4,
    PLAYER_LOGIN_QUERY_LOADQUESTSTATUS          = 5,
    PLAYER_LOGIN_QUERY_LOADDAILYQUESTSTATUS     = 6,
    PLAYER_LOGIN_QUERY_LOADREPUTATION           = 7,
    PLAYER_LOGIN_QUERY_LOADINVENTORY            = 8,
    PLAYER_LOGIN_QUERY_LOADACTIONS              = 9,
    PLAYER_LOGIN_QUERY_LOADMAILCOUNT            = 10,
    PLAYER_LOGIN_QUERY_LOADMAILDATE             = 11,
    PLAYER_LOGIN_QUERY_LOADSOCIALLIST           = 12,
    PLAYER_LOGIN_QUERY_LOADHOMEBIND             = 13,
    PLAYER_LOGIN_QUERY_LOADSPELLCOOLDOWNS       = 14,
    PLAYER_LOGIN_QUERY_LOADDECLINEDNAMES        = 15,
    PLAYER_LOGIN_QUERY_LOADGUILD                = 16,
    PLAYER_LOGIN_QUERY_LOADARENAINFO            = 17,
    PLAYER_LOGIN_QUERY_LOADACHIEVEMENTS         = 18,
    PLAYER_LOGIN_QUERY_LOADCRITERIAPROGRESS     = 19,
    PLAYER_LOGIN_QUERY_LOADEQUIPMENTSETS        = 20,
    PLAYER_LOGIN_QUERY_LOADBGDATA               = 21,
    PLAYER_LOGIN_QUERY_LOADGLYPHS               = 22,
    PLAYER_LOGIN_QUERY_LOADTALENTS              = 23,
    PLAYER_LOGIN_QUERY_LOADACCOUNTDATA          = 24,
    PLAYER_LOGIN_QUERY_LOADSKILLS               = 25,
    PLAYER_LOGIN_QUERY_LOADWEEKLYQUESTSTATUS    = 26,
    PLAYER_LOGIN_QUERY_LOADRANDOMBG             = 27,
    PLAYER_LOGIN_QUERY_LOADBANNED               = 28,
    PLAYER_LOGIN_QUERY_LOADQUESTSTATUSREW       = 29,
    PLAYER_LOGIN_QUERY_LOADINSTANCELOCKTIMES    = 30,
    PLAYER_LOGIN_QUERY_LOADSEASONALQUESTSTATUS  = 31,
    PLAYER_LOGIN_QUERY_TRANSMOGUNLOCKED         = 32,
    PLAYER_LOGIN_QUERY_TRANSMOGACTIVE           = 33,
    PLAYER_LOGIN_QUERY_TRANSMOGHISTORY          = 34,
    MAX_PLAYER_LOGIN_QUERY,
};

#endif
