DELETE FROM `string_module`
WHERE `ModuleName` = 'mod-transmogrification'
    AND `ID` BETWEEN 1 AND 40;

INSERT INTO `string_module` (`ModuleName`, `ID`, `Locale`, `Text`)
        VALUES
            -- Slot name enUS
            ('mod-transmogrification', 1, 'enUS', 'Head'), ('mod-transmogrification', 2, 'enUS', 'Shoulders'), ('mod-transmogrification', 3, 'enUS', 'Shirt'), ('mod-transmogrification', 4, 'enUS', 'Chest'), ('mod-transmogrification', 5, 'enUS', 'Waist'), ('mod-transmogrification', 6, 'enUS', 'Legs'), ('mod-transmogrification', 7, 'enUS', 'Feet'), ('mod-transmogrification', 8, 'enUS', 'Wrists'), ('mod-transmogrification', 9, 'enUS', 'Hands'), ('mod-transmogrification', 10, 'enUS', 'Back'), ('mod-transmogrification', 11, 'enUS', 'Main hand'), ('mod-transmogrification', 12, 'enUS', 'Off hand'), ('mod-transmogrification', 13, 'enUS', 'Ranged'), ('mod-transmogrification', 14, 'enUS', 'Tabard'),
            -- Slot name ruRU
            ('mod-transmogrification', 1, 'ruRU', 'Голова'), ('mod-transmogrification', 2, 'ruRU', 'Плечи'), ('mod-transmogrification', 3, 'ruRU', 'Рубашка'), ('mod-transmogrification', 4, 'ruRU', 'Грудь'), ('mod-transmogrification', 5, 'ruRU', 'Пояс'), ('mod-transmogrification', 6, 'ruRU', 'Ноги'), ('mod-transmogrification', 7, 'ruRU', 'Ступни'), ('mod-transmogrification', 8, 'ruRU', 'Запястье'), ('mod-transmogrification', 9, 'ruRU', 'Руки'), ('mod-transmogrification', 10, 'ruRU', 'Спина'), ('mod-transmogrification', 11, 'ruRU', 'Правая рука'), ('mod-transmogrification', 12, 'ruRU', 'Левая рука'), ('mod-transmogrification', 13, 'ruRU', 'Дальний бой'), ('mod-transmogrification', 14, 'ruRU', 'Гербовая накидка'),
            -- enUS Gossips
            ('mod-transmogrification', 15, 'enUS', '|TInterface/ICONS/INV_Misc_Book_11:30:30:-18:0|tHow transmogrification works'), ('mod-transmogrification', 16, 'enUS', '|TInterface/RAIDFRAME/UI-RAIDFRAME-MAINASSIST:30:30:-18:0|tManage sets'), ('mod-transmogrification', 17, 'enUS', '|TInterface/ICONS/INV_Enchant_Disenchant:30:30:-18:0|tRemove all transmogrifications'), ('mod-transmogrification', 18, 'enUS', '|TInterface/ICONS/INV_Enchant_Disenchant:30:30:-18:0|tRemove transmogrification'), ('mod-transmogrification', 19, 'enUS', '|TInterface/PaperDollInfoFrame/UI-GearManager-Undo:30:30:-18:0|tUpdate menu'), ('mod-transmogrification', 20, 'enUS', '|TInterface/ICONS/Ability_Spy:30:30:-18:0|tBack..'), ('mod-transmogrification', 21, 'enUS', 'Remove transmogrifications from all equipped items?'), ('mod-transmogrification', 22, 'enUS', 'Remove transmogrification from the slot?'), ('mod-transmogrification', 23, 'enUS', '|TInterface/GuildBankFrame/UI-GuildBankFrame-NewTab:30:30:-18:0|tSave set'), ('mod-transmogrification', 24, 'enUS', 'Using this item for transmogrify will bind it to you and make it non-refundable and non-tradeable.\nDo you wish to continue?\n\n'), ('mod-transmogrification', 25, 'enUS', '|TInterface/ICONS/INV_Misc_Book_11:30:30:-18:0|tHow sets work'), ('mod-transmogrification', 26, 'enUS', '|TInterface/ICONS/INV_Misc_Statue_02:30:30:-18:0|tUse set'), ('mod-transmogrification', 27, 'enUS', '|TInterface/PaperDollInfoFrame/UI-GearManager-LeaveItem-Opaque:30:30:-18:0|tDelete set'), ('mod-transmogrification', 28, 'enUS', 'Are you sure you want to delete '), ('mod-transmogrification', 29, 'enUS', 'Insert set name'),
            -- ruRU Gossips
            ('mod-transmogrification', 15, 'ruRU', '|TInterface/ICONS/INV_Misc_Book_11:30:30:-18:0|tКак это работает'), ('mod-transmogrification', 16, 'ruRU', '|TInterface/RAIDFRAME/UI-RAIDFRAME-MAINASSIST:30:30:-18:0|tМеню комплектов'), ('mod-transmogrification', 17, 'ruRU', '|TInterface/ICONS/INV_Enchant_Disenchant:30:30:-18:0|tУдалить все трансмогрификации'), ('mod-transmogrification', 18, 'ruRU', '|TInterface/ICONS/INV_Enchant_Disenchant:30:30:-18:0|tУдалить трасмогрификацию'), ('mod-transmogrification', 19, 'ruRU', '|TInterface/PaperDollInfoFrame/UI-GearManager-Undo:30:30:-18:0|tОбновить меню'), ('mod-transmogrification', 20, 'ruRU', '|TInterface/ICONS/Ability_Spy:30:30:-18:0|tНазад..'), ('mod-transmogrification', 21, 'ruRU', 'Удалить все трансмогрификации со всех одетых предметов?'), ('mod-transmogrification', 22, 'ruRU', 'Удалить трансмогрификацию с этого слота?'), ('mod-transmogrification', 23, 'ruRU', '|TInterface/GuildBankFrame/UI-GuildBankFrame-NewTab:30:30:-18:0|tСохранить комплект'), ('mod-transmogrification', 24, 'ruRU', 'Использование этого предмета для трансмогрификации сделать предмет персональным.\nВы хотите продолжить?\n\n.'), ('mod-transmogrification', 25, 'ruRU', '|TInterface/ICONS/INV_Misc_Book_11:30:30:-18:0|tКак работают сеты'), ('mod-transmogrification', 26, 'ruRU', '|TInterface/ICONS/INV_Misc_Statue_02:30:30:-18:0|tИспользовать комплект'), ('mod-transmogrification', 27, 'ruRU', '|TInterface/PaperDollInfoFrame/UI-GearManager-LeaveItem-Opaque:30:30:-18:0|tУдалить комплект'), ('mod-transmogrification', 28, 'ruRU', 'Вы действительно хотите удалить '), ('mod-transmogrification', 29, 'ruRU', 'Введите имя комплекта'),
            -- Strings ruRU
            ('mod-transmogrification', 30, 'ruRU', 'Предмет изменён'), ('mod-transmogrification', 31, 'ruRU', 'Пустой слот'), ('mod-transmogrification', 32, 'ruRU', 'Неверно выбранный предмет'), ('mod-transmogrification', 33, 'ruRU', 'Изначальный предмет не найден'), ('mod-transmogrification', 34, 'ruRU', 'Выбранный предмет не найден'), ('mod-transmogrification', 35, 'ruRU', 'Выбранный предмет неверный'), ('mod-transmogrification', 36, 'ruRU', 'Вам не хватает золота'), ('mod-transmogrification', 37, 'ruRU', 'Вам не хватает токенов'), ('mod-transmogrification', 38, 'ruRU', 'Трансмогрификация удалена'), ('mod-transmogrification', 39, 'ruRU', 'Трансмогрификации не найдены'), ('mod-transmogrification', 40, 'ruRU', 'Введёное имя некорректно'),
            -- Strings enUS
            ('mod-transmogrification', 30, 'enUS', 'Item transmogrified'), ('mod-transmogrification', 31, 'enUS', 'Equipment slot is empty'), ('mod-transmogrification', 32, 'enUS', 'Invalid source item selected'), ('mod-transmogrification', 33, 'enUS', 'Source item does not exist'), ('mod-transmogrification', 34, 'enUS', 'Destination item does not exist'), ('mod-transmogrification', 35, 'enUS', 'Selected items are invalid'), ('mod-transmogrification', 36, 'enUS', 'Not enough money'), ('mod-transmogrification', 37, 'enUS', 'You don\'t have enough tokens'), ('mod-transmogrification', 38, 'enUS', 'Transmogrifications removed'), ('mod-transmogrification', 39, 'enUS', 'There are no transmogrifications'), ('mod-transmogrification', 40, 'enUS', 'Invalid name inserted');
